name: Deploy

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - dev

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ganes556/lirikku:alpine

  deploy-lirikku:
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ./app-lirikku
            docker rm $(docker stop $(docker ps -a -q --filter name=lirikku-app))
            docker rmi ganes556/lirikku:alpine
            docker run -d -p 8000:8000 --env-file=.env.production --name lirikku-app ganes556/lirikku:alpine
