name: Testing

on:
  pull_request:
    branches: ['master']

  pull_request:
    branches: ['dev']
    
jobs:
  test-section-28:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Download modules
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...